export enum ProductApi {
    PRODUCT_LIST = 'PRODUCT_LIST',
    PRODUCT_LIST_BY_SMALL_PRICE = 'PRODUCT_LIST_BY_SMALL_PRICE',
    PRODUCT_LIST_BY_BIG_PRICE = 'PRODUCT_LIST_BY_BIG_PRICE',
    PRODUCT_LIST_BY_SEARCH = 'PRODUCT_LIST_BY_SEARCH',
}